### PR TITLE
Support common cloud providers auth plugins

### LINKED ISSUE #16: No Auth Provider found for name "oidc"
Hi, I was trying this but when the current context's user is authenticating with OIDC it errors out:

```bash
$ krex -v4
  _
 | |
 | | ___ __ _____  __
 | |/ / '__/ _ \ \/ /
 |   <| | |  __/>  <
 |_|\_\_|  \___/_/\_\

Kubernetes Resource Explorer

2018-07-04T20:36:20-04:00 [✖]  error during init: No Auth Provider found for name "oidc"
$
```

I tried using another context which uses basic auth and it works as expected.

PS: this is very neat and useful, thank you! Now I just need to remove the bell sound on my terminal otherwise it will drive me nuts 😃

### LINKED ISSUE #20: Configure for gcp / any other common cloud providers
We should enable support for other cloud providers
`2018-07-05T11:41:52-07:00 [✖]  No Auth Provider found for name "gcp"`

### PR DESCRIPTION
**Pull request by scottrigby**
Fixes #20, fixes #16
(more fully than #21 does - which only handles GKE).
 
Note this pulls in https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/plugins.go which is also how Helm handles this: https://github.com/kubernetes/helm/blob/master/cmd/helm/helm.go#L34

Like #21 my caveat is this is a pretty big PR, but would only be a 3-file change (as opposed to 2K+) if the #19 proposal gets merged first. Just sayin' 😅

### CODE REVIEW

**Comment by kris-nova** [comment]
bah conflict after #19

**Comment by scottrigby** [comment]
I'll rebase/fix it after I get home l8r ☺️

**Comment by scottrigby** [comment]
Rebased (2,531 less files changed 👍)

**Comment by scottrigby** [comment]
@kris-nova Should we discuss in #26 first, or do you want me to replace the vendor files in this PR in the meantime (and remove them all again later if we go that route)?

**Comment by scottrigby** [comment]
I went with option 2. Commits are well separated so it's easy to review per commit (the last one contains only the added vendor dir files).

**Pull request merged**
